import ZodiacCalculator from "@/app-views/tools/ZodiacCalculator";
import { getHreflangAlternates, baseUrl, getSEO, zodiacSEO, defaultOgImage } from "@/lib/seo-config";
import { getServerTranslations } from "@/lib/server-i18n";

export const revalidate = false;

export async function generateMetadata({ params }: { params: Promise<{ lang: string }> }) {
  const { lang } = await params;
  const seo = getSEO(zodiacSEO, lang);

  return {
    title: seo.title,
    description: seo.description,
    alternates: {
      canonical: `${baseUrl}/${lang}/tools/zodiac-calculator`,
      languages: getHreflangAlternates('/tools/zodiac-calculator'),
    },
    openGraph: {
      title: seo.title,
      description: seo.description,
      url: `${baseUrl}/${lang}/tools/zodiac-calculator`,
      siteName: 'tripcngo.com',
      images: [{ url: defaultOgImage, width: 1200, height: 630 }],
    },
    twitter: {
      card: 'summary_large_image',
      title: seo.title,
      description: seo.description,
      images: [defaultOgImage],
    },
  };
}

export default async function Page({ params }: { params: Promise<{ lang: string }> }) {
  const { lang } = await params;

  const t = getServerTranslations(lang, [
    'tools.zodiac.heroTitle',
    'tools.zodiac.heroDesc',
    'tools.zodiac.year',
    'tools.zodiac.month',
    'tools.zodiac.day',
    'tools.zodiac.button',
    'tools.zodiac.resultLabel',
    'tools.zodiac.nextBenming',
    'tools.zodiac.benmingTitle',
    'tools.zodiac.benmingDesc',
    'tools.zodiac.footerNote',
    'tools.zodiac.viewDetail',
    'tools.zodiac.currentYearTitle',
    'tools.zodiac.currentYearStart',
    'tools.zodiac.elementTag',
    'tools.zodiac.nextLabel',
    'tools.zodiac.nextPreview',
    'tools.zodiac.faq1Title',
    'tools.zodiac.faq1P1',
    'tools.zodiac.faq1P2',
    'tools.zodiac.faq1P3',
    'tools.zodiac.faq1P4',
    'tools.zodiac.nextPreviewTitle',
    'tools.zodiac.nextPreviewDesc',
    'tools.zodiac.detailTitle',
    'tools.zodiac.detailDesc',
    'tools.zodiac.birthYears',
    'tools.zodiac.personality',
    'tools.zodiac.strengths',
    'tools.zodiac.challenges',
    'tools.zodiac.career',
    'tools.zodiac.compatibility',
    'tools.zodiac.luckyNumbers',
    'tools.zodiac.travelVibe',
    'tools.zodiac.tableTitle',
    'tools.zodiac.tableDesc',
    'tools.zodiac.colZodiac',
    'tools.zodiac.colEnglish',
    'tools.zodiac.colPinyin',
    'tools.zodiac.colYears',
    'tools.zodiac.elementLegend',
    'tools.zodiac.howTitle',
    'tools.zodiac.howDesc',
    'tools.zodiac.howStep1Title',
    'tools.zodiac.howStep1Desc',
    'tools.zodiac.howStep2Title',
    'tools.zodiac.howStep2Desc',
    'tools.zodiac.howStep3Title',
    'tools.zodiac.howStep3Desc',
    'tools.zodiac.travelTitle',
    'tools.zodiac.travelDesc',
    'tools.zodiac.tip1Title',
    'tools.zodiac.tip1Desc',
    'tools.zodiac.tip2Title',
    'tools.zodiac.tip2Desc',
    'tools.zodiac.tip3Title',
    'tools.zodiac.tip3Desc',
    'tools.zodiac.tip4Title',
    'tools.zodiac.tip4Desc',
    'tools.zodiac.legendTitle',
    'tools.zodiac.legendDesc',
    'tools.zodiac.faqSectionTitle',
    'tools.zodiac.faqSectionDesc',
    'tools.zodiac.faqQ1',
    'tools.zodiac.faqA1',
    'tools.zodiac.faqQ2',
    'tools.zodiac.faqA2',
    'tools.zodiac.faqQ3',
    'tools.zodiac.faqA3',
    'tools.zodiac.faqQ4',
    'tools.zodiac.faqA4',
    'tools.zodiac.faqQ5',
    'tools.zodiac.faqA5',
    'tools.zodiac.faqQ6',
    'tools.zodiac.faqA6',
    'tools.zodiac.faqQ7',
    'tools.zodiac.faqA7',
    'tools.zodiac.faqQ8',
    'tools.zodiac.faqA8',
    'tools.zodiac.faqQ9',
    'tools.zodiac.faqA9',
    'tools.zodiac.legendAnimal1',
    'tools.zodiac.legendAnimalEn1',
    'tools.zodiac.legendText1',
    'tools.zodiac.legendAnimal2',
    'tools.zodiac.legendAnimalEn2',
    'tools.zodiac.legendText2',
    'tools.zodiac.legendAnimal3',
    'tools.zodiac.legendAnimalEn3',
    'tools.zodiac.legendText3',
    'tools.zodiac.legendAnimal4',
    'tools.zodiac.legendAnimalEn4',
    'tools.zodiac.legendText4',
    'tools.zodiac.legendAnimal5',
    'tools.zodiac.legendAnimalEn5',
    'tools.zodiac.legendText5',
    'tools.zodiac.legendAnimal6',
    'tools.zodiac.legendAnimalEn6',
    'tools.zodiac.legendText6',
    'tools.zodiac.legendAnimal7',
    'tools.zodiac.legendAnimalEn7',
    'tools.zodiac.legendText7',
    'tools.zodiac.legendAnimal8',
    'tools.zodiac.legendAnimalEn8',
    'tools.zodiac.legendText8',
    'tools.zodiac.legendAnimal9',
    'tools.zodiac.legendAnimalEn9',
    'tools.zodiac.legendText9',
    'tools.zodiac.legendAnimal10',
    'tools.zodiac.legendAnimalEn10',
    'tools.zodiac.legendText10',
    'tools.zodiac.legendAnimal11',
    'tools.zodiac.legendAnimalEn11',
    'tools.zodiac.legendText11',
    'tools.zodiac.legendAnimal12',
    'tools.zodiac.legendAnimalEn12',
    'tools.zodiac.legendText12',
    'tools.zodiac.tableAnimal1',
    'tools.zodiac.tableAnimal2',
    'tools.zodiac.tableAnimal3',
    'tools.zodiac.tableAnimal4',
    'tools.zodiac.tableAnimal5',
    'tools.zodiac.tableAnimal6',
    'tools.zodiac.tableAnimal7',
    'tools.zodiac.tableAnimal8',
    'tools.zodiac.tableAnimal9',
    'tools.zodiac.tableAnimal10',
    'tools.zodiac.tableAnimal11',
    'tools.zodiac.tableAnimal12',
    'tools.zodiac.elementMetal',
    'tools.zodiac.elementWood',
    'tools.zodiac.elementWater',
    'tools.zodiac.elementFire',
    'tools.zodiac.elementEarth',
  ]);

  return <ZodiacCalculator translations={t} />;
}
